#Set chain name EX:Leo (no spaces or hyphens, please)
Chain_Name: "Leo"

#Configure Chain
#1. Show Network stats 
#2.Configure New Genesis 
#3.Track new remote server 
#4.Deploy network Components 
Configure_New_Genesis: 2

#Choose Consensus Engine
#1.Ethash - proof of work
#2.Clique - proof of authority 
#3.XDPoS Delegated proof of stake
Consensus: 3

#Set time between each block in seconds
BlockTime: 2

#Set a reward for each epoch
EpochReward: 2000

#Set addresses to be initial masternodes
MasterNode: "xdc45B110d2F1CC8381D31661F906A9f0F3b084C657" 

#Enter the signers address.
signers: 
  - "xdcd5ec377df0fa2e44fa20e0b8e3b4aa999629b803"
  - "xdce4C4FeBE1Cb34C3490167c163C9ED92049B32B5c"
  
#Set the number of blocks of each epoch (default 900).
blockPerEpoch: 900

#Set gap -How many blocks are needed to prepare a new masternodes set before checkpoint?)
setGap: 5
#foundation address in which you hold the private key
foundationAddress: "xdc45B110d2F1CC8381D31661F906A9f0F3b084C657"

#accounts with which you control private keys to unlock the MultiSig wallet
MultiSig-Address:
  - "xdc45B110d2F1CC8381D31661F906A9f0F3b084C657"
  - "xdcd5ec377df0fa2e44fa20e0b8e3b4aa999629b803"
  - "xdce4C4FeBE1Cb34C3490167c163C9ED92049B32B5c"

#requires to confirm tx for multisig
walletConfirmations: 2

#Enter swap wallet address for fund 55 million XDC
swapWallet: "xdc45B110d2F1CC8381D31661F906A9f0F3b084C657"

#Enter the address which needs to be pre-funded
preFund:
  - "xdcd5ec377df0fa2e44fa20e0b8e3b4aa999629b803"
  - "xdce4C4FeBE1Cb34C3490167c163C9ED92049B32B5c"
  
#Enter the network ID - 72
networkID: 72

#add Nodes to subnet
Nodes:
  - "0x0000000000000000000000000000000000000000"
  - "0x0000000000000000000000000000000000000000"
  - "0x0000000000000000000000000000000000000000"
  - "0x0000000000000000000000000000000000000000"

Total_Node: 4 #(required)